version: '2'
services:
    web:
        build: .
        ports: 
            - "5000:5000"
        volumes:
            - .:/app
resources:
  requests:
    memory: "512Mi"
    cpu: 0.1
  limits:
    memory: "1024Mi"
    cpu: 1.0